spring.datasource.url=jdbc:postgresql://localhost:5432/carrentdb
spring.datasource.username=postgres
spring.datasource.password=asd125

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.show_sql=true