spring.application.name=CarRent
#H2
spring.datasource.url=jdbc:postgresql://localhost:5432/carrent
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=pass123
spring.h2.console.enabled=true
#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
#Devtools
spring.devtools.livereload.enabled=false